# Docker Compose for BBG Discord Bot
version: '3.8'

services:
  bbg-bot:
    build: .
    container_name: bbg-discord-bot
    restart: unless-stopped
    
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - MONITORING_ENABLED=true
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGODB_URI=${MONGODB_URI}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - WOS_API_SECRET=${WOS_API_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TWO_CAPTCHA_API_KEY=${TWO_CAPTCHA_API_KEY}
      - MEMBER_ROLE_ID=${MEMBER_ROLE_ID}
      - BT1_ROLE_ID=${BT1_ROLE_ID}
      - BT2_ROLE_ID=${BT2_ROLE_ID}
      - ERROR_WEBHOOK_URL=${ERROR_WEBHOOK_URL}
    
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    
    ports:
      - "3000:3000"
    
    networks:
      - bbg-network
    
    depends_on:
      - mongodb
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:6.0
    container_name: bbg-mongodb
    restart: unless-stopped
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-bbg_bot}
    
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    
    ports:
      - "27017:27017"
    
    networks:
      - bbg-network
    
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: bbg-nginx
    restart: unless-stopped
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    
    ports:
      - "80:80"
      - "443:443"
    
    networks:
      - bbg-network
    
    depends_on:
      - bbg-bot

volumes:
  mongodb_data:

networks:
  bbg-network:
    driver: bridge
